// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_aSW0IUFXa9hhDiOwh3os8Ez24twrWY',
    appId: '1:644895784866:android:59822235d77cbf158a3cfb',
    messagingSenderId: '644895784866',
    projectId: 'flutter-chat-app-d4239',
    storageBucket: 'flutter-chat-app-d4239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFzD8lhVOch8aiheoepHgR0ufsfzy-QWQ',
    appId: '1:644895784866:ios:7c61f616d4dd42ea8a3cfb',
    messagingSenderId: '644895784866',
    projectId: 'flutter-chat-app-d4239',
    storageBucket: 'flutter-chat-app-d4239.firebasestorage.app',
    iosBundleId: 'com.vedanti.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdlylZiEcQyB6ylxA18c3rlmDBXKTt1eE',
    appId: '1:644895784866:web:beed096a9b8bc3688a3cfb',
    messagingSenderId: '644895784866',
    projectId: 'flutter-chat-app-d4239',
    authDomain: 'flutter-chat-app-d4239.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d4239.firebasestorage.app',
    measurementId: 'G-GFKYK4VTMG',
  );

}